#4476 [WIP] ratelimit
beego/beego pull request #4508
Opened 2021-02-22 11:17 UTC by anoymouscoder

2021-03-02 10:46 UTC, flycash reviewed
Could you provide the code of `rate limit filter` ? I want to know how users use those algorithms

2021-03-07 05:33 UTC, anoymouscoder commented
How to use:
```
// Construct limiter with options such as rate and capacity.
opts := []LimiterOption{WithRate(1 * time.Millisecond), WithCapacity(1)}
limiter := NewLimiter(opts)
// Register limiter to specify route 
err := handler.InsertFilter("*", web.BeforeRouter, limiter)
```

2021-03-07 11:40 UTC, flycash requested changes
Good!

2021-03-07 11:40 UTC, flycash commented on server/web/filter/ratelimit/token_bucket.go
> +func NewTokenBucket(opts []BucketOption) Bucket {
Using `opts ... BucketOption`. In general, when we use `option design pattern`, we always use `opts...XXXXOpt`

2021-03-08 09:03 UTC, anoymouscoder commented on server/web/filter/ratelimit/limiter.go
> +	b, ok := l.buckets[key]
Why is a read lock needed here?

2021-03-09 01:58 UTC, flycash approved these changes
Please resolve the conflict

2021-03-09 13:49 UTC, anoymouscoder commented
@flycash Conflicts resolved.

2021-03-12 15:24 UTC, merged