增强模板函数 eq,lt 支持 uint 和 int 类型的比较
beego/beego pull request #4601
Opened 2021-05-08 17:18 UTC by jimashi

2021-05-10 02:27 UTC, flycash requested changes
Please add more unit tests for this pull request.

2021-05-10 02:27 UTC, flycash commented
Please update the commit message to english :)

2021-05-10 02:41 UTC, jimashi commented
> Please update the commit message to english :)

Ok,thinks!

2021-05-10 02:53 UTC, jimashi commented on server/web/templatefunc.go
> +				fieldV.SetInt(int64(x))
I think i agree with you.

2021-05-13 05:13 UTC, flycash requested changes
Please add unit tests for those change.

2021-05-13 05:13 UTC, flycash commented on server/web/templatefunc.go
> +				fieldV.SetInt(int64(x))
So please revert this change.

2021-05-13 05:33 UTC, jimashi commented on server/web/templatefunc.go
> +				fieldV.SetInt(int64(x))
不好意思，我原来是以为那个PR挂在那里，你们不合并就可以了。“revert"是得我这边操作吗，要重新push吗

2021-05-13 05:47 UTC, jimashi commented on server/web/templatefunc.go
> +				fieldV.SetInt(int64(x))
我这边fork的版本不能“revert”了，我看到原来最新版本的 beego 源代码里，你们注释了“注解路由”的功能，我提交到自己的fork仓库时，又把那个注解路由的功能恢复了。在push到git仓库的时候提示失败，我就“强制”push到git仓库上。现在要怎么还原回来到你们原来的版本呢？

2021-05-13 06:12 UTC, jimashi commented on server/web/templatefunc.go
> +				fieldV.SetInt(int64(x))
> So please revert this change.

Can you help me delete my PR? I can't find a way to do it.

2021-05-13 06:21 UTC, closed without merging