postFrom
beego/beego pull request #4605
Opened 2021-05-12 03:34 UTC by wandercn

add postFrom with submit formdata

It's the same as this function http.PostForm in net/http.

2021-05-12 03:59 UTC, wandercn commented
encoding/xml 这个包怎么提示Security 安全风险。我没改这个代码，原来就是使用的这个包 @astaxie

2021-05-13 05:08 UTC, flycash requested changes
please add unit tests.

2021-05-13 05:08 UTC, flycash commented on client/httplib/httplib.go
> +func (b *BeegoHTTPRequest) PostForm(fromdata string) (*BeegoHTTPRequest, error) {
`formdata`?

2021-05-13 05:08 UTC, flycash commented on client/httplib/httplib.go
> +		return b, berror.Wrap(err, InvalidFormData, "fromdata format error")
form, not from

2021-05-13 05:08 UTC, flycash commented on client/httplib/httplib.go
> +func (b *BeegoHTTPRequest) PostForm(fromdata string) (*BeegoHTTPRequest, error) {
I think maybe users want to use `map` as the `formdata`.
If we declare `formdata`, I guess that users need to build the string in most cases. Maybe using `map` would be better.

2021-05-13 05:09 UTC, flycash commented
Please fix CI problem

2021-05-22 07:22 UTC, closed without merging