Feat: add orm opentelemetry filter
beego/beego pull request #4950
Opened 2022-05-19 04:04 UTC by Dokiys

issue:#4944 
I've referred `opentracing/filter.go` to add this pr. But i'm not sure how to test this featrue, although there is an unit test.

2022-05-20 14:44 UTC, flycash commented on client/orm/filter/opentelemetry/filter.go
> +	"github.com/beego/beego/v2/client/orm"
please format these imports

2022-05-20 14:44 UTC, flycash commented on client/orm/filter/opentelemetry/filter.go
> +
remove the unnecessary empty line

2022-05-20 14:44 UTC, flycash commented on client/orm/filter/opentelemetry/filter.go
> +}
remove this function and change to use option pattern. You can learn the Go option pattern via google

2022-05-21 08:56 UTC, Dokiys commented on client/orm/filter/opentelemetry/filter.go
> +
👌OK

2022-05-23 15:41 UTC, Dokiys commented
@flycash Hello, I fix the test. But about golangci-lint error I have no idea. I'm not sure which file cause the error. I use gofumpt and gofmt to check both files there is no changes.

2022-05-24 13:28 UTC, flycash commented
you can click the `Details` for more information. 
And do remember add this MR into change log

2022-05-24 13:35 UTC, flycash commented
And you can find the golant-ci issues in `File changed`

2022-05-26 05:50 UTC, Dokiys commented
> And you can find the golant-ci issues in `File changed`

@flycash Thanks. I've modified again.

2022-05-27 14:19 UTC, flycash commented
![image](https://user-images.githubusercontent.com/9923838/170717836-cc6a2730-d4a3-4302-94db-1d731c0b2ca9.png)
Hi, can you help to fix this?

2022-05-29 10:52 UTC, Dokiys commented
@flycash hi, I tried my best to fix this, but I still don't know why these code cause the error.  I just add as `client/orm/filter/opentracing/filter.go`.

2022-05-29 10:57 UTC, flycash requested changes

2022-05-29 10:57 UTC, flycash commented on client/orm/filter/opentelemetry/filter.go
> +func (builder *FilterChainBuilder) buildSpan(span otelTrace.Span, ctx context.Context, inv *orm.Invocation) {
please make the `ctx` as the first parameter

2022-05-30 15:20 UTC, merged