feat: add get all tasks function
beego/beego pull request #4999
Opened 2022-06-27 04:19 UTC by qwganker

2022-06-27 13:11 UTC, flycash requested changes

2022-06-27 13:11 UTC, flycash commented on task/task.go
> +	for _, tasker := range m.adminTaskList {
why do you use reflection here?

2022-06-27 13:11 UTC, flycash commented on task/task_test.go
> +	for _, t := range l {
use assertion in tests, and do not use any printing function, including `fmt.Println`

2022-06-28 03:06 UTC, qwganker commented
@flycash 

pls, review again,

2022-06-29 02:21 UTC, qwganker commented
> I mean, why you use reflection in your code? you want to make a copy? but why we need a copy?

ok, now, i use another way to implment it that add GetTask() function into Tasker{} interface

2022-06-29 02:29 UTC, qwganker commented
`DeepSource`  scan rule is changed?

2022-06-29 13:41 UTC, flycash commented on task/task.go
> +	GetTask(ctx context.Context) *Task
don't need this function

2022-06-29 13:41 UTC, flycash commented on task/task.go
> +func (m *taskManager) GetAllTasks() []*Task {
it should return the Tasker, and the users do the type assertion by themselves.
And the `taskManager` is a private structure, how do users call this function?

2022-06-30 01:48 UTC, qwganker commented
@flycash  I updated the implement,  GetAllTasks() function will export to public, user  can use it like this
```golang
import beego "github.com/beego/beego/v2/task"

...

beego.AddTask("test1", t1)
beego.AddTask("test2", t2)

...

tasks := beego.GetAllTasks()
for _, task := range tasks {
  rv := reflect.ValueOf(task)
  t := rv.Interface().(*Task)
  fmt.Println(t)
}



```

2022-07-02 08:34 UTC, flycash requested changes

2022-07-02 08:34 UTC, flycash commented on task/task.go
> +	var l []Tasker
```
l := make([]Tasker, 0, len(m.adminTaskList))
```
We can specify the capacity to avoid the memory allocation

2022-07-02 08:35 UTC, flycash commented
And do remember add one change log into `.CHANGELOG` file like this:
![image](https://user-images.githubusercontent.com/9923838/176993266-a53e7481-75e2-43c7-bc71-4e79b4315b3b.png)

2022-07-02 09:20 UTC, qwganker commented
@flycash  I has been updated, pls review again

2022-07-02 10:12 UTC, flycash approved these changes

2022-07-02 10:18 UTC, merged