feature extend readthrough for cache module
beego/beego pull request #5116
Opened 2022-12-09 15:24 UTC by Stone-afk

2022-12-11 05:57 UTC, flycash commented on client/cache/read_through.go
> +	mutex      sync.RWMutex
you don't need the mutex. Just let the Cache to protect its resources.

2022-12-12 02:45 UTC, flycash requested changes

2022-12-12 02:45 UTC, flycash commented on client/cache/read_through.go
> +// Get cache from readThroughCache
Get will try to call the LoadFunc to load data if the Cache returns value nil or non-nil error.

2022-12-12 02:45 UTC, flycash commented on client/cache/read_through.go
> +func (c *readThroughCache) GetMulti(ctx context.Context, keys []string) ([]any, error) {
You should call the c.Cache.GetMulti, it looks like:
```go
vals, err := c.Cache.GetMulti()
if err != nil {
    // call load functions
}
```

2022-12-12 02:45 UTC, flycash commented on client/cache/read_through.go
> +func (c *readThroughCache) GetMulti(ctx context.Context, keys []string) ([]any, error) {
And then the comment should be:
GetMulti will call the LoadFunc to load data if the Cache.GetMulti returns non-nil error. You should check the concrete type of Cache to learn the cases that the GetMulti function will returns non-nil error.

2022-12-12 02:45 UTC, flycash commented on client/cache/error_code.go
> +Invalid loadFunc.
Invalid load function for read-through pattern decorator.
You should pass a valid(non-nil) load function when initiate the decorator instance

2022-12-12 02:45 UTC, flycash commented on client/cache/read_through.go
> +				err, KeyNotExist, "cache unable to load data")
Define a new error instead of using KeyNotExit, i.e FailedToLoadData. As you can see, the key may be exist.

2022-12-12 02:45 UTC, flycash commented on client/cache/read_through.go
> +	LoadFunc   func(ctx context.Context, key string) (any, error)
you can make them as private

2022-12-12 02:45 UTC, flycash commented on client/cache/read_through.go
> +func NewReadThroughCache(cache Cache, expiration time.Duration,
How about using a flag to indicate if the GetMulti will reuse the LoadFunction? looks like:
```go
if c.applyForGetMulti {
    // call load func
}
```
And the default value is false. I want to make the users to pay more attention to the GetMulti function.
They must call the NewReadThroughCache(..., ApplyForGetMulti), so they can understand we will call the LoadFunc by iterating the keys.

ApplyForGetMulti should be option pattern.

2022-12-12 02:45 UTC, flycash commented on client/cache/read_through.go
> +				err, KeyNotExist, "cache unable to load data")
The error code shout start with 4 because it's user's input error(the load func is invalid)

2022-12-12 13:29 UTC, Stone-afk commented on client/cache/read_through.go
> +func (c *readThroughCache) GetMulti(ctx context.Context, keys []string) ([]any, error) {
这里直接使用 GetMulti 有种情况就是 err 为nil， 但是 vals 里的值为空接口，所以  GetMulti  本质上是无解的，所以考虑放弃支持 GetMulti

2022-12-13 06:19 UTC, flycash approved these changes

2022-12-13 06:20 UTC, flycash commented
@Stone-afk add this MR into CHANGLOG.md

2022-12-13 06:26 UTC, flycash commented
and please fix the golang-ci issues

2022-12-15 13:24 UTC, merged