WIP: feature add singleflight cache
beego/beego pull request #5119
Opened 2022-12-11 03:46 UTC by Stone-afk

add singleflight cache, test case not supplemented

2022-12-15 13:25 UTC, flycash commented
please  rebase to origin/develop and fix the conflicts

2022-12-15 16:52 UTC, Stone-afk commented
目前针对 ssdb 的并发测试，不管设置的 value 是啥最终都会会持续返回 “1”

2022-12-15 16:54 UTC, Stone-afk commented
`
func testSingleflightCacheConcurrencyGet(t *testing.T, bm cache.Cache) {
	key, value := "key3", "value3"
	db := &MockOrm{keysMap: map[string]int{key: 1}, kvs: map[string]any{key: value}}
	c, err := cache.NewSingleflightCache(bm, 10*time.Second,
		func(ctx context.Context, key string) (any, error) {
			val, er := db.Load(key)
			if er != nil {
				return nil, er
			}
			return val, nil
		})
	assert.Nil(t, err)

	var wg sync.WaitGroup
	wg.Add(10)
	for i := 0; i < 10; i++ {
		go func() {
			defer wg.Done()
			val, err := c.Get(context.Background(), key)
			if err != nil {
				t.Error(err)
			}
			assert.Equal(t, value, val)
		}()
	}
	wg.Wait()
}
`

2022-12-15 16:55 UTC, Stone-afk commented
```
func testSingleflightCacheConcurrencyGet(t *testing.T, bm cache.Cache) {
	key, value := "key3", "value3"
	db := &MockOrm{keysMap: map[string]int{key: 1}, kvs: map[string]any{key: value}}
	c, err := cache.NewSingleflightCache(bm, 10*time.Second,
		func(ctx context.Context, key string) (any, error) {
			val, er := db.Load(key)
			if er != nil {
				return nil, er
			}
			return val, nil
		})
	assert.Nil(t, err)


	var wg sync.WaitGroup
	wg.Add(10)
	for i := 0; i < 10; i++ {
		go func() {
			defer wg.Done()
			val, err := c.Get(context.Background(), key)
			if err != nil {
				t.Error(err)
			}
			assert.Equal(t, value, val)
		}()
	}
	wg.Wait()
}

```

2022-12-17 15:01 UTC, flycash requested changes
remove other tests. Just keep singleflight_test

2022-12-17 15:03 UTC, flycash commented on client/cache/singleflight.go
> +	LoadFunc   func(ctx context.Context, key string) (any, error)
make them private

2022-12-18 05:07 UTC, flycash commented on client/cache/singleflight.go
> +		val, err, _ = s.group.Do(key, func() (interface{}, error) {
I think you need to delete the key after loading data. So when the key is expired again, goroutine will load data one more time

2022-12-20 08:32 UTC, flycash approved these changes

2022-12-20 08:32 UTC, merged