cache/redis: use redisConfig to receive incoming JSON (previously using a map)
beego/beego pull request #5268
Opened 2023-06-29 16:04 UTC by Handkerchiefs-t

- use redisConfig to receive incoming JSON (previously using a map)
- change "timeout" to "idleTimeout"

2023-06-30 15:36 UTC, flycash requested changes
Put this merge request to CHANGELOG file

2023-06-30 15:36 UTC, flycash commented on client/cache/redis/redis.go
> +	DefaultIdleTimeout = time.Second * 180
make these two as private:
```go
defaultMaxIdle = 3
defaultIdleTimeout = time.Second * 180
```

2023-06-30 15:36 UTC, flycash commented on client/cache/redis/redis.go
> +	IdleTimeoutStr string `json:"timeout"`
Timeout time.Duration `json:"timeout"`

2023-06-30 15:36 UTC, flycash commented on client/cache/redis/redis.go
> +	idleTimeout time.Duration
while use `Timeout time.Duration` you don't need this field, and please remove it

2023-06-30 15:36 UTC, flycash commented on client/cache/redis/redis.go
> +	IdleTimeoutStr string `json:"timeout"`
Add comment: `Timeout used for idle connection`

2023-07-02 11:07 UTC, Handkerchiefs-t commented
@flycash 
I made the following modifications to the code:
1. Use the string type to receive the config and convert them in the **redisConfig.parse** method.
2. Still use the string type to receive the **timeout**.
3. Set **defaultMaxIdle** and **defaultTimeout** as private.

2023-07-02 14:08 UTC, merged