refactor: ORM Builder pattern that supports select statement
beego/beego pull request #5414
Opened 2023-09-17 07:04 UTC by smx-Morgan

2023-09-21 03:34 UTC, flycash requested changes

2023-09-21 03:34 UTC, flycash commented on client/orm/qb/select.go
> +	s.model, _ = s.cache.GetByMd(&t)
Do not ignore this error

2023-09-21 03:34 UTC, flycash commented on client/orm/qb/select.go
> +	}
refactor this part that extract it as a new function

2023-09-21 03:34 UTC, flycash commented on client/orm/qb/select.go
> +	if e == nil {
you can add one more case:
```go
case nil:
    return nil
```

2023-09-21 03:34 UTC, flycash commented on client/orm/qb/select.go
> +func (s *Selector[T]) buildColumn(c Column, useAlias bool) error {
remove useAlias parameter, currently it always be true

2023-09-21 03:34 UTC, flycash commented on client/orm/qb/select.go
> +	sb        strings.Builder
using `internal/buffers`.

2023-09-22 14:02 UTC, flycash commented on client/orm/qb/query.go
> +type Executor interface {
remove this interface because it's useless now

2023-09-24 04:52 UTC, flycash commented
@smx-Morgan please check those comments.

2023-09-24 05:36 UTC, smx-Morgan commented
got it, the code is currently being modified

2023-09-25 11:39 UTC, flycash commented
and please resolve the conflicts

2023-09-25 14:35 UTC, closed without merging